### ISSUE TITLE
Issues with npolar-api-error

### ISSUE THREAD

**Issue by rexso** [npolar/angular-npolar#7]
Error messages emitted through **npolar-api-error** does not automatically disappear, and are _not_ possible to close manually.

Also, the error messages are wrong (not overwritable?) and should yield the error message from the requested service. See [UserRegisterController](https://github.com/npolar/npdc-user/blob/f42f351d38b64896b4e18d58c718d35d01b7ded7/src/register/UserRegisterController.js#L50) for an example where the current error messages are useless to the user.

**Comment by cnrdh** [comment]
This happens when the request crashes (ie. because the server crashes => 500/502 => CORS failure => HTTP status 0 (zero)

This is the ugly message you see then
{"status":0,"method":"POST","uri":"https://api.npolar.no/user/register","headers":{},"time":"2015-10-28T09:29:14.219Z","body":{"error":{"explanation":"Failed accessing Npolar API https://api.npolar.no/user/register"}}}

**Comment by cnrdh** [comment]
However, you are not supposed to use NpolarApiMessage like this. The messaging system was designed so that app developers can forget about errors and focus on the sunny days.

Take home **messages** ;)
- Don't (usually) trap API errors responses, it's already done by the HTTP interceptor
- Don't (in particular) send "npolar-api-*" messages, it's also done by the HTTP interceptor

Instead, you may
- Send "npolar-info" message
- Send and capture your own events, eg. "sicas-error"

(PS: Why the toast is not closeable on status 0 is still a mystery, but that's a separate story: see #3  and #4)

**Comment by baelter** [comment]
Bug in mdToast when two toast are added in the same digest cycle:
https://github.com/angular/material/issues/3103

Work around, don't do that.
